### ISSUE TITLE
Doesn't open in browser

### ISSUE THREAD

**Issue by mittalyashu** [mixn/carbon-now-cli#27] opened 2018-08-29 11:21 UTC
![2018-08-29_16-50-11](https://user-images.githubusercontent.com/29014463/44784553-ad4c0d80-abab-11e8-93aa-90be8e965739.gif)

**Comment by mittalyashu** [comment] 2018-08-29 11:32
> It‘s been a few days without hearing from you, I was already wondering when you‘d open the next issue. 😉😄

Sorry for keep you waiting 😜😂

> Does the 2nd example the browser?

Nope, it doesn't even work, if we open the terminal as administrator.

**Comment by mixn** [comment] 2018-08-29 11:36
> Sorry for keep you waiting 😜😂

😏 😃 

As previously, I can’t reproduce this — it works with just `-o` and with `-s` + `-e` + `-o`.

What is the content of `BtnLink.js`?

**Comment by mittalyashu** [comment] 2018-08-29 11:38
> What is the content of BtnLink.js?

Just a simple button component.

![carbon_2018-08-29_17-08-05](https://user-images.githubusercontent.com/29014463/44785318-1d5b9300-abae-11e8-9098-94b8d7b5186e.png)

**Comment by mixn** [comment] 2018-08-29 11:39
@mittalyashu Please post the code here.

**Comment by mittalyashu** [comment] 2018-08-29 11:39
```js
import React from 'react'
import { Link as GatsbyLink } from 'gatsby'
import styled from 'styled-components'

const Link = styled(GatsbyLink)`
  color: #00d664;
`;

const ExternalLink = Link.withComponent('a');

const BtnLink = ({className, name, link}) => {
  const internal = /^\/(?!\/)/.test(link)

  if (internal) {
    return (
      <Link className={className} to={link}>{name}</Link>
    )
  } else {
    return (
      <ExternalLink className={className} href={link}>{name}</ExternalLink>
    )
  }
}

export default BtnLink
```

**Comment by mixn** [comment] 2018-08-29 11:41
Works without issues for me. https://carbon.now.sh/?bg=%23ADB7C1&t=seti&wt=none&l=javascript&ds=false&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=48px&ph=32px&ln=false&fm=Hack&fs=18px&lh=133%25&si=false&code=import%2520React%2520from%2520%27react%27%250Aimport%2520%257B%2520Link%2520as%2520GatsbyLink%2520%257D%2520from%2520%27gatsby%27%250Aimport%2520styled%2520from%2520%27styled-components%27%250A%250Aconst%2520Link%2520%253D%2520styled(GatsbyLink)%2560%250A%2520%2520color%253A%2520%252300d664%253B%250A%2560%253B%250A%250Aconst%2520ExternalLink%2520%253D%2520Link.withComponent(%27a%27)%253B%250A%250Aconst%2520BtnLink%2520%253D%2520(%257BclassName%252C%2520name%252C%2520link%257D)%2520%253D%253E%2520%257B%250A%2520%2520const%2520internal%2520%253D%2520%252F%255E%255C%252F(%253F!%255C%252F)%252F.test(link)%250A%250A%2520%2520if%2520(internal)%2520%257B%250A%2520%2520%2520%2520return%2520(%250A%2520%2520%2520%2520%2520%2520%253CLink%2520className%253D%257BclassName%257D%2520to%253D%257Blink%257D%253E%257Bname%257D%253C%252FLink%253E%250A%2520%2520%2520%2520)%250A%2520%2520%257D%2520else%2520%257B%250A%2520%2520%2520%2520return%2520(%250A%2520%2520%2520%2520%2520%2520%253CExternalLink%2520className%253D%257BclassName%257D%2520href%253D%257Blink%257D%253E%257Bname%257D%253C%252FExternalLink%253E%250A%2520%2520%2520%2520)%250A%2520%2520%257D%250A%257D%250A%250Aexport%2520default%2520BtnLink&es=2x&wm=false&ts=false

![btnlink-1c153d3e6c](https://user-images.githubusercontent.com/672237/44785448-386bda00-ab91-11e8-9dac-d78bb5a7b034.png)

**Comment by mixn** [comment] 2018-08-29 11:43
`carbon-now-cli` uses [`opn`](https://github.com/sindresorhus/opn) under the hood. There is a [CLI for `open`](https://github.com/sindresorhus/opn-cli), please try that out on its own. I don’t think this issue is on `carbon-now-cli`’s front.

**Comment by mittalyashu** [comment] 2018-08-29 11:45
> carbon-now-cli uses opn under the hood. There is a CLI for open, please try that out on its own. I don’t think this issue is on carbon-now-cli’s front.

I will install it and try.

![2018-08-29_17-14-27](https://user-images.githubusercontent.com/29014463/44785621-27ca5c80-abaf-11e8-9fcf-5f2f0155e57f.gif)

**Comment by mixn** [comment] 2018-08-29 11:46
Also, if there is a `~/carbon-now.json` present, post it here pls.

**Comment by mittalyashu** [comment] 2018-08-29 11:48
I have installed the `opn` package and it worked, but `carbon-now-cli` is still not working.

![2018-08-29_17-17-38](https://user-images.githubusercontent.com/29014463/44785719-85f73f80-abaf-11e8-8f67-c8d59d34ee58.gif)

**Comment by mittalyashu** [comment] 2018-08-29 11:49
Here's the `.carbon-now.json` file.

```json
{
  "carbon": {
    "t": "seti",
    "bg": "rgba(191,220,238,1)",
    "wt": "none",
    "wc": true,
    "fm": "Fira Code",
    "fs": "16px",
    "ln": false,
    "ds": true,
    "dsyoff": "20px",
    "dsblur": "73px",
    "wa": true,
    "lh": "133%",
    "pv": "48px",
    "ph": "32px",
    "si": false,
    "wm": false,
    "es": "4x",
    "type": "png"
  },
  "latest-preset": {
    "t": "seti",
    "bg": "rgba(191,220,238,1)",
    "wt": "none",
    "wc": true,
    "fm": "Fira Code",
    "fs": "16px",
    "ln": false,
    "ds": true,
    "dsyoff": "20px",
    "dsblur": "73px",
    "wa": true,
    "lh": "133%",
    "pv": "48px",
    "ph": "32px",
    "si": false,
    "wm": false,
    "es": "4x",
    "type": "png"
  }
}
```

**Comment by mixn** [comment] 2018-08-29 11:54
Please try opening it from a script using the [`opn` package](https://github.com/sindresorhus/opn).

**Comment by mittalyashu** [comment] 2018-08-29 11:55
> Please try opening a site from a script using the opn package.

Already tried that and it's working, see the `gif` below.

![image](https://user-images.githubusercontent.com/29014463/44785719-85f73f80-abaf-11e8-8f67-c8d59d34ee58.gif)

**Comment by mixn** [comment] 2018-08-29 11:58
@mittalyashu No, you haven’t. :) Make a `.js` file, use the `opn` module to open a page there and run the `.js` file with `node file-name.js`.

Also, there is only [a single line of code that uses `opn`](https://github.com/mixn/carbon-now-cli/blob/master/cli.js#L156). ¯\_(ツ)_/¯ Wonder how this could fail on `carbon-now-cli`’s end.

**Comment by mittalyashu** [comment] 2018-08-29 12:08
> No, you haven’t. :) Make a .js file, use the opn module to open a page there and run the .js file with node file-name.js.

Roger that 🤘🏻

![2018-08-29_17-37-06](https://user-images.githubusercontent.com/29014463/44786614-4f6ef400-abb2-11e8-8b53-0261f46318e0.gif)

Nothing happened

**Comment by mixn** [comment] 2018-08-29 12:18
You’re using `opn-cli`, not the `opn` module directly. I’ll guide you through once more:

1. Create a folder and enter it
2. Run `npm init -y`
3. Run `npm i opn --save`
4. Create a `index.js` file and do this inside 

```
const opn = require('opn');

opn('https://google.com');
```

5. Run `index.js` file with `node index.js` — this should open google.com

**Comment by mittalyashu** [comment] 2018-08-29 12:28
It worked 

![2018-08-29_17-57-55](https://user-images.githubusercontent.com/29014463/44787567-24d26a80-abb5-11e8-82a3-1430f9b1f548.gif)

**Comment by mixn** [comment] 2018-08-29 12:44
Hm. Please delete `.carbon-now.json` and run with `-o` again.

**Comment by mittalyashu** [comment] 2018-08-29 13:06
I have deleted the `.carbon-now.json` file, run the command again `carbon-now btnlink.js -o`, the command didn't work and the `.json` file was created again.

**Comment by mixn** [comment] 2018-08-30 11:55
I’ll leave this open for a bit to see if somebody experiences the same problem.

**Comment by rahulkp220** [comment] 2018-09-13 10:18
Not working for me on OS X as well. Isn't opening the browser, says 
```
↓ Opening in browser [skipped]
 ✖ Fetching beautiful image
   → net::ERR_CONNECTION_CLOSED at https://carbon.now.sh/?bg=%23ADB7C1&code=%252F%2A%2520Copyright%25EF%25BC%25882%25EF%25BC%2589%25202018%2…

  Error: Sending code to https://carbon.now.sh went wrong.

  This is mostly due to:

  – Insensical input like `--start 10 --end 2`
  – Carbon being down or taking too long to respond
  – Your internet connection not working or being too slow
```

**Comment by mixn** [comment] 2018-09-13 10:53
@rahulkp220 Do you happen to be behind a proxy?

I can’t debug/fix this because it hasn’t happened to me a single time pre or post release. More info or fixes are welcome. :)

**Comment by rahulkp220** [comment] 2018-09-13 11:00
Okay, the message was a success,
```
↓ Fetching beautiful image [skipped]

  Done!

  Browser opened — finish your image there! 😌```

However, I couldn't see any file in the browser. It said connection refused. No I am not behind a proxy

**Comment by mixn** [comment] 2018-09-13 11:50
@rahulkp220 Can you confirm that you’ve run

```
carbon-now foo.js -o
```

and are running `v1.1.0` of `carbon-now-cli`? And that it didn’t open a browser for you?

**Comment by mixn** [comment] 2018-09-13 12:08
@mittalyashu @rahulkp220 Pls both confirm that the browser of your choice is [exists / is available in your `$PATH`](https://github.com/sindresorhus/opn/issues/66#issuecomment-325191836). Also, there is [this](https://github.com/sindresorhus/opn/issues/79), which is still open. And you should try [closing your browser before running `carbon-now`](https://github.com/sindresorhus/opn/issues/41#issuecomment-283317327), just to see if it will work.

**Comment by rahulkp220** [comment] 2018-09-13 14:14
@mixn Yes, I used the exact same command as you mentioned and I am using the latest version
```
carbon-now --version
1.1.0
```
Plus doing a `open -n -a "Google Chrome" --args "https://google.com" --incognito` works absolutely fine on my system.

**Comment by mittalyashu** [comment] 2018-09-13 16:54
@mixn should I create a server, just like this https://github.com/mixn/carbon-now-cli/issues/27#issuecomment-416931691 to test it.

**Comment by mixn** [comment] 2018-09-14 14:17
@mittalyashu @rahulkp220 I’m in 🇨🇦 atm, so not really able to look at this much more closely. Will do when back. :) Feel free to debug/further inspect as it’s reproducible on your system.

**Comment by mixn** [comment] 2018-10-16 10:58
@mittalyashu There was a [bug](https://github.com/mixn/carbon-now-cli/pull/35) with `--start` and `--end` that I missed and your original comment in this thread is based on that. Could you try running it without the parameters, e.g.

```
carbon-now foobar.js --open
```

**Comment by mittalyashu** [comment] 2018-10-16 11:48
![image](https://user-images.githubusercontent.com/29014463/47014301-79cb3f80-d167-11e8-8fb3-90a66796d5ab.png)

Tried this but still it didn't work.

**Comment by mixn** [comment] 2018-10-16 11:51
Ok, thought it couldn’t hurt to ask. :)

**Comment by mixn** [comment] 2018-10-23 22:31
@mittalyashu 

Ok, so I actually set up a Windows VM 😅🔫😆 and tested this — and it worked! 🙂

![opn-windows](https://user-images.githubusercontent.com/672237/47394470-4bc79b80-d723-11e8-951a-666334218d18.gif)

There was *one* time out of like ~12 where it failed. I have no idea why but I am like 95% certain this is related to [some of the issues I’ve mentioned here](https://github.com/mixn/carbon-now-cli/issues/27#issuecomment-420983685).

And as I’ve said before, `opn` is used in exactly **one line of code**. Hence, this issue is not caused by `carbon-now-cli`.

@rahulkp220 And when it comes to macOS… I’ve never had this command fail me, ever, on three different versions of macOS. So I’m really sorry, but I absolutely can’t “fix” it, since it’s unreproducable for me. Sorry. 😢🙏

**Closed** 2018-10-26 16:44 UTC
Labels: feedback wanted

**Comment by mittalyashu** [comment] 2018-10-26 17:28
Do I need to update `carbon-now-cli` locally?

**Comment by mixn** [comment] 2018-10-26 17:32
@mittalyashu I didn’t change anything related to this, as I’ve stated in my previous comment. It worked on Windows, macOS, Unix and the issue seems to be related to the `opn` module.
