### ISSUE TITLE
Ability to change the default settings without building from the source.

### ISSUE THREAD

**Issue by farkaskid** [mixn/carbon-now-cli#8] opened 2018-07-11 03:05 UTC
An options of changing the default config is not immediately visible without building from the source.
Most of the people after some initial playing around would settle for a custom default settings.

I think an option should be there for that.

**Comment by mixn** [comment] 2018-07-11 09:48
Hi @farkaskid, thanks for your input. :)

As far as I understand, I think this is a duplicate of #2  and something that I’m planning to implement soon. Or am I not understanding correctly? :)

**Comment by farkaskid** [comment] 2018-07-11 10:48
Yeah, it almost the same. What I had in mind was ability to make 'profiles' by the combination of your fav settings and then ability to set any one of the profiles as default. It will be like making and switching themes is a text editor.
This is a superset of #2 . #2 proposal is much cleaner and feels lightweight, I like that.

**Comment by mixn** [comment] 2018-07-11 23:34
Glad you like it. :) The idea of profiles has been (briefly) discussed in #2, too. Just keep an eye out on #2 !

**Closed** 2018-07-11 23:35 UTC
