### ISSUE TITLE
--from-clipboard specify language

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [mixn/carbon-now-cli#75] opened 2022-02-13 14:27 UTC
Hey guys,

Is there a way to specify the language when using `--from-clipboard`, e.g. I want to tell carbon my clipboard contains `python` code.

Thanks :)

Francesco

**Comment by mixn** [comment] 2023-04-29 10:11
Hey @FrancescoSaverioZuppichini, I’ll close this for now as it is (sort of) a duplicate of #59. :) Please check the comment I will make there since I want to implement this now and need some feedback prior to it. :) 

Thanks in advance!

**Closed by mixn** 2023-04-29 10:11 UTC
