### ISSUE TITLE
Doesn't work in Windows 10

### ISSUE THREAD

**Issue by Suleman-Elahi** [mixn/carbon-now-cli#28] opened 2018-09-13 04:40 UTC
![image](https://user-images.githubusercontent.com/24384996/45467293-814c9280-b73c-11e8-8d45-16213ece3c46.png)

**Comment by mixn** [comment] 2018-09-13 07:05
Hi @Suleman-Elahi, thanks for reporting. :) 

This looks like a duplicate of #9, which is fixed. Please try running with `-h`, e.g. `carbon-now test.html -i -h`. Should work without issues.

**Comment by mittalyashu** [comment] 2018-09-13 10:58
> Side-note/off-topic: Every unit should be a valid CSS measuring unit, e.g. px. Referring to Vertical padding: 20 here. :)

@mixn Since I have to deal with this issue also, so can you make `px` as default measuring unit.

**Comment by mixn** [comment] 2018-09-13 11:46
@mittalyashu 

> @mixn Since I have to deal with this issue also, so can you make `px` as default measuring unit.

Very likely not, because this is not an issue — it just allows for all units by requiring more explicitness.

Adding `px` by default would mean having to remove it in all other cases. Also, presets! :)

**Comment by mittalyashu** [comment] 2018-09-13 11:59
> Adding px by default would mean having to remove it in all other cases. Also, presets! 😄😉

I see. 🤔

**Closed** 2018-09-14 05:44 UTC
