### ISSUE TITLE
File can be found here: <path>?

### ISSUE THREAD

**Issue by mittalyashu** [mixn/carbon-now-cli#24] opened 2018-08-11 18:22 UTC
![image](https://user-images.githubusercontent.com/29014463/43994860-a13a0b20-9dc1-11e8-809c-51eb8055c3b1.png)

**Comment by mixn** [comment] 2018-08-11 18:54
Duplicate of #9 and as it seems likely an issue with Puppeteer.

**Closed by mixn** 2018-08-11 18:54 UTC
