### ISSUE TITLE
Why opening the browser? Can't we render it locally?

### ISSUE THREAD

**Issue by alrevuelta** [mixn/carbon-now-cli#63] opened 2020-10-19 20:10 UTC
Just found this amazing project, but find odd that it has to open the browser in order to render the image and then download it. Isn't it possible to run it locally? Faster rendering, no internet connection needed, and no dependancy to an external service.

I'm sure the code from `carbon-now` can be reused somehow. Not a web-dev myself, but happy to help if anyone wants to team up.

**Comment by mixn** [comment] 2023-05-09 17:54
Duplicate of #15. And for everyone who reads this, please also see #83.

**Closed by mixn** 2023-05-09 17:54 UTC
Labels: feature-request
