### ISSUE TITLE
Using custom theme

### ISSUE THREAD

**Issue by Rokko11** [mixn/carbon-now-cli#47] opened 2019-04-10 21:22 UTC
Hi,

there are [many themes](https://github.com/dawnlabs/carbon/blob/master/lib/constants.js) like dracula, base16-dark, etc... defined in carbon-now-sh, but I also can define a custom theme there.

Is it possible to use a custom theme with carbon-now-cli?

Kind regards,
Rokko

**Comment by mixn** [comment] 2019-04-10 22:11
Duplicate of feature request #46. :)

**Closed** 2019-04-10 22:12 UTC
