### ISSUE TITLE
there is no image file as the output said

### ISSUE THREAD

**Issue by csrgxtu** [mixn/carbon-now-cli#14] opened 2018-07-12 07:03 UTC
![image](https://user-images.githubusercontent.com/5053620/42617570-b30861c0-85e4-11e8-8fde-2266aef46724.png)

**Comment by mixn** [comment] 2018-07-12 09:01
Thanks for reporting @csrgxtu. :) This is a duplicate of #10, so have keep an eye out on that one. 😇 Hope I get it fixed soon!

**Closed** 2018-07-12 09:01 UTC
